// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU5gDzfumPQWpAPO7afkV-rGcrVONLOoo',
    appId: '1:207309187279:web:efa56910c26b169817afba',
    messagingSenderId: '207309187279',
    projectId: 'cineshelf-d4b82',
    authDomain: 'cineshelf-d4b82.firebaseapp.com',
    storageBucket: 'cineshelf-d4b82.firebasestorage.app',
    measurementId: 'G-0VKR46DSXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSZqioNpk6RzmZqX2wwVVd58BoK9rsdE',
    appId: '1:207309187279:android:c9c80ecd5a31a08917afba',
    messagingSenderId: '207309187279',
    projectId: 'cineshelf-d4b82',
    storageBucket: 'cineshelf-d4b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxIN5-wFJMp2VIsiLxN_Q6X41NyQQuX1I',
    appId: '1:207309187279:ios:ad4cbf4b8f6d86bb17afba',
    messagingSenderId: '207309187279',
    projectId: 'cineshelf-d4b82',
    storageBucket: 'cineshelf-d4b82.firebasestorage.app',
    iosBundleId: 'com.example.cineShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxIN5-wFJMp2VIsiLxN_Q6X41NyQQuX1I',
    appId: '1:207309187279:ios:ad4cbf4b8f6d86bb17afba',
    messagingSenderId: '207309187279',
    projectId: 'cineshelf-d4b82',
    storageBucket: 'cineshelf-d4b82.firebasestorage.app',
    iosBundleId: 'com.example.cineShelf',
  );
}
